import "./globals.css";

// importing ggogle fonts using next js
import { Josefin_Sans } from "next/font/google";

const josef = Josefin_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  display: "swap",
});
export const metadata = {
  title: "Kmyaan Digital Bussiness",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // childern act as props
  return (
    <html lang="en">
      <head>
        {/* link are for slickslider taken from react slick slider docs */}
        <link
          rel="stylesheet"
          type="text/css"
          charset="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </head>
      <body className={josef.className}>{children}</body>
    </html>
  );
}

// className={josef.className} this is to use font on our website
